SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `gagou` ;
CREATE SCHEMA IF NOT EXISTS `gagou` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `gagou` ;

-- -----------------------------------------------------
-- Table `Pagina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagina` ;

SHOW WARNINGS;
CREATE  TABLE IF NOT EXISTS `Pagina` (
  `PaginaId` INT NOT NULL AUTO_INCREMENT ,
  `PaginaUrlHash` VARCHAR(32) NOT NULL ,
  `PaginaConteudo` LONGTEXT NOT NULL ,
  `PaginaUrl` TEXT NOT NULL ,
  PRIMARY KEY (`PaginaId`) )
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PaginaUrl_UNIQUE` ON `Pagina` (`PaginaUrlHash` ASC) ;

SHOW WARNINGS;
USE `gagou` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;